baseURL = 'https://munekata-lab.github.io/'
languageCode = 'ja'
defaultContentLanguage = "ja"
hasCJKLanguage = true
title = 'Munekata Laboratory'
theme = 'hugo-flex'
canonifyurls = true
publishDir = "docs"

[site]
title = 'Munekata Laboratory'